language: dart

dart:
  - stable
#  - dev

env:
  matrix:
#    - PUB=DOWNGRADE
    - PUB=UPGRADE
#  - GOOGLE_CLOUD_DATASTORE_LOCAL_DEV_SERVER_EXECUTABLE=_install/google_cloud_datastore_dev_server/gcd-v1beta2-rev1-2.1.1/gcd.sh

script: dart -c tool/grind.dart travis

# Speed up builds by using containerization. Disable this if you need to use
# sudo in your scripts.
sudo: required

#branches:
#  only:
#    - master

cache:
  directories:
    - $HOME/.pub-cache

before_install:
  - echo exit 101 | sudo tee /usr/sbin/policy-rc.d
  - sudo chmod +x /usr/sbin/policy-rc.d

install:
  - sudo apt-get update
  - sudo apt-get install -y -qq --no-install-recommends openjdk-7-jre-headless
  - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip && unzip -d $HOME google-cloud-sdk.zip && rm google-cloud-sdk.zip
  - sudo $HOME/google-cloud-sdk/install.sh --usage-reporting=true --path-update=true --bash-completion=true --rc-path=/.bashrc --disable-installation-options
  - sudo $HOME/google-cloud-sdk/bin/gcloud --quiet components update pkg-go pkg-python pkg-java preview alpha beta app
  - sudo $HOME/google-cloud-sdk/bin/gcloud --quiet config set component_manager/disable_update_check true
  - sudo chown -R $USER $HOME/google-cloud-sdk
  - wget http://storage.googleapis.com/gcd/tools/gcd-v1beta2-rev1-2.1.1.zip && unzip -d $HOME/google_cloud_datastore_dev_server gcd-v1beta2-rev1-2.1.1.zip && rm gcd-v1beta2-rev1-2.1.1.zip
  - sudo chown -R $USER $HOME/google_cloud_datastore_dev_server
  - pub upgrade
  - ls -la /home/travis/google_cloud_datastore_dev_server/gcd-v1beta2-rev1-2.1.1

