name: bwu_datastore_launcher
version: 0.2.2
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: Simplify starting and stopping local Cloud Datastore server(s) from unit tests.
homepage: https://github.com/bwu-dart/bwu_datastore_launcher
environment:
  sdk: ">=1.8.0-dev.3.0 <2.0.0"

dependencies:
  path: ^1.3.0
  bwu_utils_server: ^0.0.4

dev_dependencies:
  unittest: any
