name: bwu_datastore_launcher
version: 0.3.2-dev.0
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: Simplify starting and stopping local Cloud Datastore server(s) from unit tests.
homepage: https://github.com/bwu-dart/bwu_datastore_launcher
environment:
  sdk: ">=1.8.0-dev.3.0 <2.0.0"

dependencies:
  path: ^1.3.0
  bwu_utils: ^0.1.0-dev.1
  logging: ^0.9.3
  logging_handlers: ^0.8.0
  quiver_log: ^1.0.3

dev_dependencies:
  unittest: ^0.12.0-beta.1
  analyzer: ^0.25.0-dev.3
  dart_style: '>=0.1.7 <0.2.0'

dependency_overrides:
  analyzer: ^0.25.0-dev.3
  bwu_utils:
    path: ../bwu_utils
  linter:
    git: git@github.com:dart-lang/linter.git
  matcher: ^0.12.0-alpha.0
#  unittest: ^0.12.0-beta.1

